### ISSUE TITLE
When you click on the Facebook icon nothing happens.

### ISSUE THREAD

**Issue by RuthSupuran** [peviitor-ro/ui-js#162] opened 2022-11-16 11:09 UTC
## Precondition
URL: https://beta.peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
Website is loaded without any issues

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Scroll down to footer

#### Expected Result
Page is scrolled without any issues

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Tap on Facebook icon

#### Expected Result
User should be redirected to &quot;Pe Viitor&quot; facebook page 

#### Actual Result
When you click on the Facebook icon nothing happens.

**Comment by RuthSupuran** [comment] 2022-11-16 11:09
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=12484)
- Test [Tapping Facebook footer logo](https://web.testquality.com/site/peviitor/project/12763/runs/172020?resultId=3037263) in Run [Run 043](https://web.testquality.com/site/peviitor/project/12763/runs/172020) (linked to Cycle [V04-S1](https://web.testquality.com/site/peviitor/project/12763/cycles/27716)).

**Comment by biancacristurean** [comment] 2022-11-19 08:40
Duplicate of #180

**Closed by biancacristurean** 2022-11-19 08:40 UTC
Labels: bug, TestQuality
